[tool.poetry]
name = "zplgrid"
version = "0.1.0"
description = "Compile layout templates into ZPL II."
readme = "README.md"
authors = ["Nathaniel"]
packages = [{ include = "zplgrid" }]

[tool.poetry.dependencies]
python = ">=3.10"
jsonschema = ">=4.26.0"
fastapi = "^0.141.1"
uvicorn = "^0.30.0"
pillow = "^12.3.0"
requests = "^2.32.0"
segno = "^1.6.6"
pylibdmtx = "^0.1.10"
pyyaml = "^6.0.3"
python-dotenv = "^1.2.3"
zeroconf = "^0.147.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.2"
httpx = "^0.28.1"

[tool.pytest.ini_options]
norecursedirs = [
  ".pytest_cache",
  "pytest-cache-files-*",
]

[build-system]
requires = ["poetry-core>=1.9.1"]
build-backend = "poetry.core.masonry.api"
